### ISSUE TITLE
Recommended hardware to get the data

### ISSUE THREAD

**Issue by mathigatti** [lbugnon/emoHR#2]
Hi! Amazing project, thanks for sharing.

Do you have some recommended smart band or related piece of hardware to measure continuously and extract the raw data?

**Comment by lbugnon** [comment]
Hi, the requirement is to have a reliable beat to beat signal (the time between beats, for each beat).
This can be done with any ECG recording device , including commercial chest straps used for sports (such as the polar H7)
Another option is a wrist wearable, which usually are more affected by movement noise but they are less invasive. I didn't tried it for this task but the Scotche Rythm24 record a nice signal. There are less options here because they usually doesn't provide the raw signal

**Comment by mathigatti** [comment]
Awesome, thank you very much!!
